// Code generated by https://github.com/alis-exchange/protoc-gen-go-meta. DO NOT EDIT.
//
// Source: alis/usage/v1/usage.proto
// Plugin version: v0.0.1
//
// Generated on: 2026-09-01 13:23:49 UTC

package usage

const ()
