// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: alis/usage/v1/usage.proto

package usage

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProductUsage_WindowKind int32

const (
	ProductUsage_WINDOW_KIND_UNSPECIFIED ProductUsage_WindowKind = 0
	ProductUsage_WINDOW_KIND_ROLLING_24H ProductUsage_WindowKind = 1
	ProductUsage_WINDOW_KIND_ROLLING_7D  ProductUsage_WindowKind = 2
	ProductUsage_WINDOW_KIND_ROLLING_30D ProductUsage_WindowKind = 3
)

// Enum value maps for ProductUsage_WindowKind.
var (
	ProductUsage_WindowKind_name = map[int32]string{
		0: "WINDOW_KIND_UNSPECIFIED",
		1: "WINDOW_KIND_ROLLING_24H",
		2: "WINDOW_KIND_ROLLING_7D",
		3: "WINDOW_KIND_ROLLING_30D",
	}
	ProductUsage_WindowKind_value = map[string]int32{
		"WINDOW_KIND_UNSPECIFIED": 0,
		"WINDOW_KIND_ROLLING_24H": 1,
		"WINDOW_KIND_ROLLING_7D":  2,
		"WINDOW_KIND_ROLLING_30D": 3,
	}
)

func (x ProductUsage_WindowKind) Enum() *ProductUsage_WindowKind {
	p := new(ProductUsage_WindowKind)
	*p = x
	return p
}

func (x ProductUsage_WindowKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProductUsage_WindowKind) Descriptor() protoreflect.EnumDescriptor {
	return file_alis_usage_v1_usage_proto_enumTypes[0].Descriptor()
}

func (ProductUsage_WindowKind) Type() protoreflect.EnumType {
	return &file_alis_usage_v1_usage_proto_enumTypes[0]
}

func (x ProductUsage_WindowKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProductUsage_WindowKind.Descriptor instead.
func (ProductUsage_WindowKind) EnumDescriptor() ([]byte, []int) {
	return file_alis_usage_v1_usage_proto_rawDescGZIP(), []int{0, 0}
}

type ProductUsage struct {
	state            protoimpl.MessageState     `protogen:"open.v1"`
	Product          string                     `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	ProductProjectId string                     `protobuf:"bytes,2,opt,name=product_project_id,json=productProjectId,proto3" json:"product_project_id,omitempty"`
	SnapshotTime     *timestamppb.Timestamp     `protobuf:"bytes,3,opt,name=snapshot_time,json=snapshotTime,proto3" json:"snapshot_time,omitempty"`
	Windows          []*ProductUsage_Window     `protobuf:"bytes,4,rep,name=windows,proto3" json:"windows,omitempty"`
	DailyTrend       []*ProductUsage_DailyCount `protobuf:"bytes,5,rep,name=daily_trend,json=dailyTrend,proto3" json:"daily_trend,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ProductUsage) Reset() {
	*x = ProductUsage{}
	mi := &file_alis_usage_v1_usage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductUsage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductUsage) ProtoMessage() {}

func (x *ProductUsage) ProtoReflect() protoreflect.Message {
	mi := &file_alis_usage_v1_usage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductUsage.ProtoReflect.Descriptor instead.
func (*ProductUsage) Descriptor() ([]byte, []int) {
	return file_alis_usage_v1_usage_proto_rawDescGZIP(), []int{0}
}

func (x *ProductUsage) GetProduct() string {
	if x != nil {
		return x.Product
	}
	return ""
}

func (x *ProductUsage) GetProductProjectId() string {
	if x != nil {
		return x.ProductProjectId
	}
	return ""
}

func (x *ProductUsage) GetSnapshotTime() *timestamppb.Timestamp {
	if x != nil {
		return x.SnapshotTime
	}
	return nil
}

func (x *ProductUsage) GetWindows() []*ProductUsage_Window {
	if x != nil {
		return x.Windows
	}
	return nil
}

func (x *ProductUsage) GetDailyTrend() []*ProductUsage_DailyCount {
	if x != nil {
		return x.DailyTrend
	}
	return nil
}

type ProductUsage_Window struct {
	state         protoimpl.MessageState          `protogen:"open.v1"`
	Kind          ProductUsage_WindowKind         `protobuf:"varint,1,opt,name=kind,proto3,enum=alis.usage.v1.ProductUsage_WindowKind" json:"kind,omitempty"`
	StartTime     *timestamppb.Timestamp          `protobuf:"bytes,2,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       *timestamppb.Timestamp          `protobuf:"bytes,3,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Deployments   []*ProductUsage_DeploymentUsage `protobuf:"bytes,4,rep,name=deployments,proto3" json:"deployments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductUsage_Window) Reset() {
	*x = ProductUsage_Window{}
	mi := &file_alis_usage_v1_usage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductUsage_Window) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductUsage_Window) ProtoMessage() {}

func (x *ProductUsage_Window) ProtoReflect() protoreflect.Message {
	mi := &file_alis_usage_v1_usage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductUsage_Window.ProtoReflect.Descriptor instead.
func (*ProductUsage_Window) Descriptor() ([]byte, []int) {
	return file_alis_usage_v1_usage_proto_rawDescGZIP(), []int{0, 0}
}

func (x *ProductUsage_Window) GetKind() ProductUsage_WindowKind {
	if x != nil {
		return x.Kind
	}
	return ProductUsage_WINDOW_KIND_UNSPECIFIED
}

func (x *ProductUsage_Window) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *ProductUsage_Window) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *ProductUsage_Window) GetDeployments() []*ProductUsage_DeploymentUsage {
	if x != nil {
		return x.Deployments
	}
	return nil
}

type ProductUsage_DeploymentUsage struct {
	state           protoimpl.MessageState      `protogen:"open.v1"`
	GoogleProjectId string                      `protobuf:"bytes,1,opt,name=google_project_id,json=googleProjectId,proto3" json:"google_project_id,omitempty"`
	Totals          *ProductUsage_MethodStats   `protobuf:"bytes,2,opt,name=totals,proto3" json:"totals,omitempty"`
	Methods         []*ProductUsage_MethodUsage `protobuf:"bytes,3,rep,name=methods,proto3" json:"methods,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ProductUsage_DeploymentUsage) Reset() {
	*x = ProductUsage_DeploymentUsage{}
	mi := &file_alis_usage_v1_usage_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductUsage_DeploymentUsage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductUsage_DeploymentUsage) ProtoMessage() {}

func (x *ProductUsage_DeploymentUsage) ProtoReflect() protoreflect.Message {
	mi := &file_alis_usage_v1_usage_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductUsage_DeploymentUsage.ProtoReflect.Descriptor instead.
func (*ProductUsage_DeploymentUsage) Descriptor() ([]byte, []int) {
	return file_alis_usage_v1_usage_proto_rawDescGZIP(), []int{0, 1}
}

func (x *ProductUsage_DeploymentUsage) GetGoogleProjectId() string {
	if x != nil {
		return x.GoogleProjectId
	}
	return ""
}

func (x *ProductUsage_DeploymentUsage) GetTotals() *ProductUsage_MethodStats {
	if x != nil {
		return x.Totals
	}
	return nil
}

func (x *ProductUsage_DeploymentUsage) GetMethods() []*ProductUsage_MethodUsage {
	if x != nil {
		return x.Methods
	}
	return nil
}

type ProductUsage_MethodUsage struct {
	state           protoimpl.MessageState    `protogen:"open.v1"`
	Package         string                    `protobuf:"bytes,1,opt,name=package,proto3" json:"package,omitempty"`
	Service         string                    `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	Method          string                    `protobuf:"bytes,3,opt,name=method,proto3" json:"method,omitempty"`
	CloudRunService string                    `protobuf:"bytes,4,opt,name=cloud_run_service,json=cloudRunService,proto3" json:"cloud_run_service,omitempty"`
	Stats           *ProductUsage_MethodStats `protobuf:"bytes,5,opt,name=stats,proto3" json:"stats,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ProductUsage_MethodUsage) Reset() {
	*x = ProductUsage_MethodUsage{}
	mi := &file_alis_usage_v1_usage_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductUsage_MethodUsage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductUsage_MethodUsage) ProtoMessage() {}

func (x *ProductUsage_MethodUsage) ProtoReflect() protoreflect.Message {
	mi := &file_alis_usage_v1_usage_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductUsage_MethodUsage.ProtoReflect.Descriptor instead.
func (*ProductUsage_MethodUsage) Descriptor() ([]byte, []int) {
	return file_alis_usage_v1_usage_proto_rawDescGZIP(), []int{0, 2}
}

func (x *ProductUsage_MethodUsage) GetPackage() string {
	if x != nil {
		return x.Package
	}
	return ""
}

func (x *ProductUsage_MethodUsage) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *ProductUsage_MethodUsage) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *ProductUsage_MethodUsage) GetCloudRunService() string {
	if x != nil {
		return x.CloudRunService
	}
	return ""
}

func (x *ProductUsage_MethodUsage) GetStats() *ProductUsage_MethodStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

type ProductUsage_MethodStats struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RequestCount    int64                  `protobuf:"varint,1,opt,name=request_count,json=requestCount,proto3" json:"request_count,omitempty"`
	ErrorCount      int64                  `protobuf:"varint,2,opt,name=error_count,json=errorCount,proto3" json:"error_count,omitempty"`
	ErrorRate       float64                `protobuf:"fixed64,3,opt,name=error_rate,json=errorRate,proto3" json:"error_rate,omitempty"`
	LatencyP50      float64                `protobuf:"fixed64,4,opt,name=latency_p50,json=latencyP50,proto3" json:"latency_p50,omitempty"`
	LatencyP95      float64                `protobuf:"fixed64,5,opt,name=latency_p95,json=latencyP95,proto3" json:"latency_p95,omitempty"`
	LatencyP99      float64                `protobuf:"fixed64,6,opt,name=latency_p99,json=latencyP99,proto3" json:"latency_p99,omitempty"`
	DistinctCallers int64                  `protobuf:"varint,7,opt,name=distinct_callers,json=distinctCallers,proto3" json:"distinct_callers,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ProductUsage_MethodStats) Reset() {
	*x = ProductUsage_MethodStats{}
	mi := &file_alis_usage_v1_usage_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductUsage_MethodStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductUsage_MethodStats) ProtoMessage() {}

func (x *ProductUsage_MethodStats) ProtoReflect() protoreflect.Message {
	mi := &file_alis_usage_v1_usage_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductUsage_MethodStats.ProtoReflect.Descriptor instead.
func (*ProductUsage_MethodStats) Descriptor() ([]byte, []int) {
	return file_alis_usage_v1_usage_proto_rawDescGZIP(), []int{0, 3}
}

func (x *ProductUsage_MethodStats) GetRequestCount() int64 {
	if x != nil {
		return x.RequestCount
	}
	return 0
}

func (x *ProductUsage_MethodStats) GetErrorCount() int64 {
	if x != nil {
		return x.ErrorCount
	}
	return 0
}

func (x *ProductUsage_MethodStats) GetErrorRate() float64 {
	if x != nil {
		return x.ErrorRate
	}
	return 0
}

func (x *ProductUsage_MethodStats) GetLatencyP50() float64 {
	if x != nil {
		return x.LatencyP50
	}
	return 0
}

func (x *ProductUsage_MethodStats) GetLatencyP95() float64 {
	if x != nil {
		return x.LatencyP95
	}
	return 0
}

func (x *ProductUsage_MethodStats) GetLatencyP99() float64 {
	if x != nil {
		return x.LatencyP99
	}
	return 0
}

func (x *ProductUsage_MethodStats) GetDistinctCallers() int64 {
	if x != nil {
		return x.DistinctCallers
	}
	return 0
}

type ProductUsage_DailyCount struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Date            string                 `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	GoogleProjectId string                 `protobuf:"bytes,2,opt,name=google_project_id,json=googleProjectId,proto3" json:"google_project_id,omitempty"`
	RequestCount    int64                  `protobuf:"varint,3,opt,name=request_count,json=requestCount,proto3" json:"request_count,omitempty"`
	ErrorCount      int64                  `protobuf:"varint,4,opt,name=error_count,json=errorCount,proto3" json:"error_count,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ProductUsage_DailyCount) Reset() {
	*x = ProductUsage_DailyCount{}
	mi := &file_alis_usage_v1_usage_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductUsage_DailyCount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductUsage_DailyCount) ProtoMessage() {}

func (x *ProductUsage_DailyCount) ProtoReflect() protoreflect.Message {
	mi := &file_alis_usage_v1_usage_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductUsage_DailyCount.ProtoReflect.Descriptor instead.
func (*ProductUsage_DailyCount) Descriptor() ([]byte, []int) {
	return file_alis_usage_v1_usage_proto_rawDescGZIP(), []int{0, 4}
}

func (x *ProductUsage_DailyCount) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *ProductUsage_DailyCount) GetGoogleProjectId() string {
	if x != nil {
		return x.GoogleProjectId
	}
	return ""
}

func (x *ProductUsage_DailyCount) GetRequestCount() int64 {
	if x != nil {
		return x.RequestCount
	}
	return 0
}

func (x *ProductUsage_DailyCount) GetErrorCount() int64 {
	if x != nil {
		return x.ErrorCount
	}
	return 0
}

var File_alis_usage_v1_usage_proto protoreflect.FileDescriptor

const file_alis_usage_v1_usage_proto_rawDesc = "" +
	"\n" +
	"\x19alis/usage/v1/usage.proto\x12\ralis.usage.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xca\v\n" +
	"\fProductUsage\x12\x18\n" +
	"\aproduct\x18\x01 \x01(\tR\aproduct\x12,\n" +
	"\x12product_project_id\x18\x02 \x01(\tR\x10productProjectId\x12?\n" +
	"\rsnapshot_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\fsnapshotTime\x12<\n" +
	"\awindows\x18\x04 \x03(\v2\".alis.usage.v1.ProductUsage.WindowR\awindows\x12G\n" +
	"\vdaily_trend\x18\x05 \x03(\v2&.alis.usage.v1.ProductUsage.DailyCountR\n" +
	"dailyTrend\x1a\x85\x02\n" +
	"\x06Window\x12:\n" +
	"\x04kind\x18\x01 \x01(\x0e2&.alis.usage.v1.ProductUsage.WindowKindR\x04kind\x129\n" +
	"\n" +
	"start_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\x12M\n" +
	"\vdeployments\x18\x04 \x03(\v2+.alis.usage.v1.ProductUsage.DeploymentUsageR\vdeployments\x1a\xc1\x01\n" +
	"\x0fDeploymentUsage\x12*\n" +
	"\x11google_project_id\x18\x01 \x01(\tR\x0fgoogleProjectId\x12?\n" +
	"\x06totals\x18\x02 \x01(\v2'.alis.usage.v1.ProductUsage.MethodStatsR\x06totals\x12A\n" +
	"\amethods\x18\x03 \x03(\v2'.alis.usage.v1.ProductUsage.MethodUsageR\amethods\x1a\xc4\x01\n" +
	"\vMethodUsage\x12\x18\n" +
	"\apackage\x18\x01 \x01(\tR\apackage\x12\x18\n" +
	"\aservice\x18\x02 \x01(\tR\aservice\x12\x16\n" +
	"\x06method\x18\x03 \x01(\tR\x06method\x12*\n" +
	"\x11cloud_run_service\x18\x04 \x01(\tR\x0fcloudRunService\x12=\n" +
	"\x05stats\x18\x05 \x01(\v2'.alis.usage.v1.ProductUsage.MethodStatsR\x05stats\x1a\x80\x02\n" +
	"\vMethodStats\x12#\n" +
	"\rrequest_count\x18\x01 \x01(\x03R\frequestCount\x12\x1f\n" +
	"\verror_count\x18\x02 \x01(\x03R\n" +
	"errorCount\x12\x1d\n" +
	"\n" +
	"error_rate\x18\x03 \x01(\x01R\terrorRate\x12\x1f\n" +
	"\vlatency_p50\x18\x04 \x01(\x01R\n" +
	"latencyP50\x12\x1f\n" +
	"\vlatency_p95\x18\x05 \x01(\x01R\n" +
	"latencyP95\x12\x1f\n" +
	"\vlatency_p99\x18\x06 \x01(\x01R\n" +
	"latencyP99\x12)\n" +
	"\x10distinct_callers\x18\a \x01(\x03R\x0fdistinctCallers\x1a\x92\x01\n" +
	"\n" +
	"DailyCount\x12\x12\n" +
	"\x04date\x18\x01 \x01(\tR\x04date\x12*\n" +
	"\x11google_project_id\x18\x02 \x01(\tR\x0fgoogleProjectId\x12#\n" +
	"\rrequest_count\x18\x03 \x01(\x03R\frequestCount\x12\x1f\n" +
	"\verror_count\x18\x04 \x01(\x03R\n" +
	"errorCount\"\x7f\n" +
	"\n" +
	"WindowKind\x12\x1b\n" +
	"\x17WINDOW_KIND_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17WINDOW_KIND_ROLLING_24H\x10\x01\x12\x1a\n" +
	"\x16WINDOW_KIND_ROLLING_7D\x10\x02\x12\x1b\n" +
	"\x17WINDOW_KIND_ROLLING_30D\x10\x03B!Z\x1fgo.alis.build/common/alis/usageb\x06proto3"

var (
	file_alis_usage_v1_usage_proto_rawDescOnce sync.Once
	file_alis_usage_v1_usage_proto_rawDescData []byte
)

func file_alis_usage_v1_usage_proto_rawDescGZIP() []byte {
	file_alis_usage_v1_usage_proto_rawDescOnce.Do(func() {
		file_alis_usage_v1_usage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_alis_usage_v1_usage_proto_rawDesc), len(file_alis_usage_v1_usage_proto_rawDesc)))
	})
	return file_alis_usage_v1_usage_proto_rawDescData
}

var file_alis_usage_v1_usage_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_alis_usage_v1_usage_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_alis_usage_v1_usage_proto_goTypes = []any{
	(ProductUsage_WindowKind)(0),         // 0: alis.usage.v1.ProductUsage.WindowKind
	(*ProductUsage)(nil),                 // 1: alis.usage.v1.ProductUsage
	(*ProductUsage_Window)(nil),          // 2: alis.usage.v1.ProductUsage.Window
	(*ProductUsage_DeploymentUsage)(nil), // 3: alis.usage.v1.ProductUsage.DeploymentUsage
	(*ProductUsage_MethodUsage)(nil),     // 4: alis.usage.v1.ProductUsage.MethodUsage
	(*ProductUsage_MethodStats)(nil),     // 5: alis.usage.v1.ProductUsage.MethodStats
	(*ProductUsage_DailyCount)(nil),      // 6: alis.usage.v1.ProductUsage.DailyCount
	(*timestamppb.Timestamp)(nil),        // 7: google.protobuf.Timestamp
}
var file_alis_usage_v1_usage_proto_depIdxs = []int32{
	7,  // 0: alis.usage.v1.ProductUsage.snapshot_time:type_name -> google.protobuf.Timestamp
	2,  // 1: alis.usage.v1.ProductUsage.windows:type_name -> alis.usage.v1.ProductUsage.Window
	6,  // 2: alis.usage.v1.ProductUsage.daily_trend:type_name -> alis.usage.v1.ProductUsage.DailyCount
	0,  // 3: alis.usage.v1.ProductUsage.Window.kind:type_name -> alis.usage.v1.ProductUsage.WindowKind
	7,  // 4: alis.usage.v1.ProductUsage.Window.start_time:type_name -> google.protobuf.Timestamp
	7,  // 5: alis.usage.v1.ProductUsage.Window.end_time:type_name -> google.protobuf.Timestamp
	3,  // 6: alis.usage.v1.ProductUsage.Window.deployments:type_name -> alis.usage.v1.ProductUsage.DeploymentUsage
	5,  // 7: alis.usage.v1.ProductUsage.DeploymentUsage.totals:type_name -> alis.usage.v1.ProductUsage.MethodStats
	4,  // 8: alis.usage.v1.ProductUsage.DeploymentUsage.methods:type_name -> alis.usage.v1.ProductUsage.MethodUsage
	5,  // 9: alis.usage.v1.ProductUsage.MethodUsage.stats:type_name -> alis.usage.v1.ProductUsage.MethodStats
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_alis_usage_v1_usage_proto_init() }
func file_alis_usage_v1_usage_proto_init() {
	if File_alis_usage_v1_usage_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_alis_usage_v1_usage_proto_rawDesc), len(file_alis_usage_v1_usage_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_alis_usage_v1_usage_proto_goTypes,
		DependencyIndexes: file_alis_usage_v1_usage_proto_depIdxs,
		EnumInfos:         file_alis_usage_v1_usage_proto_enumTypes,
		MessageInfos:      file_alis_usage_v1_usage_proto_msgTypes,
	}.Build()
	File_alis_usage_v1_usage_proto = out.File
	file_alis_usage_v1_usage_proto_goTypes = nil
	file_alis_usage_v1_usage_proto_depIdxs = nil
}
