// Code generated by https://github.com/alis-exchange/protoc-gen-go-meta. DO NOT EDIT.
//
// Source: alis/open/validation/v1/validation.proto
// Plugin version: v0.0.1
//
// Generated on: 2026-09-01 07:55:21 UTC

package validation

const (
	// ValidationService_RetrieveRules_FullMethodDescription returns the description of the alis.open.validation.v1.ValidationService.RetrieveRules method.
	ValidationService_RetrieveRules_FullMethodDescription = ""
	// ValidationService_ValidateMessage_FullMethodDescription returns the description of the alis.open.validation.v1.ValidationService.ValidateMessage method.
	ValidationService_ValidateMessage_FullMethodDescription = ""
)
