// Code generated by https://github.com/alis-exchange/protoc-gen-go-meta. DO NOT EDIT.
//
// Source: alis/open/in/v1/in.proto
// Plugin version: v0.0.1
//
// Generated on: 2026-09-02 08:18:46 UTC

package inpb

const ()
