// Code generated by https://github.com/alis-exchange/protoc-gen-go-meta. DO NOT EDIT.
//
// Source: alis/open/in/v1/in.proto
// Plugin version: v0.0.1
//
// Generated on: 2026-08-24 16:24:05 UTC

package in

const ()
