// Code generated by https://github.com/alis-exchange/protoc-gen-go-meta. DO NOT EDIT.
//
// Source: alis/agui/scheduler/v1/scheduler.proto
// Plugin version: v0.0.1
//
// Generated on: 2026-07-28 15:50:32 UTC

package scheduler

const (
	// SchedulerService_GetIamPolicy_FullMethodDescription returns the description of the alis.agui.scheduler.v1.SchedulerService.GetIamPolicy method.
	SchedulerService_GetIamPolicy_FullMethodDescription = ""
	// SchedulerService_SetIamPolicy_FullMethodDescription returns the description of the alis.agui.scheduler.v1.SchedulerService.SetIamPolicy method.
	SchedulerService_SetIamPolicy_FullMethodDescription = ""
	// SchedulerService_AddIamBindings_FullMethodDescription returns the description of the alis.agui.scheduler.v1.SchedulerService.AddIamBindings method.
	SchedulerService_AddIamBindings_FullMethodDescription = ""
	// SchedulerService_RemoveIamBindings_FullMethodDescription returns the description of the alis.agui.scheduler.v1.SchedulerService.RemoveIamBindings method.
	SchedulerService_RemoveIamBindings_FullMethodDescription = ""
	// SchedulerService_CreateCron_FullMethodDescription returns the description of the alis.agui.scheduler.v1.SchedulerService.CreateCron method.
	SchedulerService_CreateCron_FullMethodDescription = ""
	// SchedulerService_ListCrons_FullMethodDescription returns the description of the alis.agui.scheduler.v1.SchedulerService.ListCrons method.
	SchedulerService_ListCrons_FullMethodDescription = ""
	// SchedulerService_GetCron_FullMethodDescription returns the description of the alis.agui.scheduler.v1.SchedulerService.GetCron method.
	SchedulerService_GetCron_FullMethodDescription = ""
	// SchedulerService_UpdateCron_FullMethodDescription returns the description of the alis.agui.scheduler.v1.SchedulerService.UpdateCron method.
	SchedulerService_UpdateCron_FullMethodDescription = ""
	// SchedulerService_DeleteCron_FullMethodDescription returns the description of the alis.agui.scheduler.v1.SchedulerService.DeleteCron method.
	SchedulerService_DeleteCron_FullMethodDescription = ""
	// SchedulerService_RunCron_FullMethodDescription returns the description of the alis.agui.scheduler.v1.SchedulerService.RunCron method.
	SchedulerService_RunCron_FullMethodDescription = ""
)
