// Code generated by https://github.com/alis-exchange/protoc-gen-go-meta. DO NOT EDIT.
//
// Source: alis/open/options/v1/options.proto
// Plugin version: v0.0.1
//
// Generated on: 2026-08-14 10:30:08 UTC

package options

const ()
