// Code generated by https://github.com/alis-exchange/protoc-gen-go-meta. DO NOT EDIT.
//
// Source: alis/open/support/v1/attachments.proto
// Plugin version: v0.0.1
//
// Generated on: 2026-08-03 16:32:36 UTC

package support

const (
	// PublicAttachmentsService_UploadImage_FullMethodDescription returns the description of the alis.open.support.v1.PublicAttachmentsService.UploadImage method.
	PublicAttachmentsService_UploadImage_FullMethodDescription = ""
)
