// Code generated by https://github.com/alis-exchange/protoc-gen-go-meta. DO NOT EDIT.
//
// Source: alis/open/support/v1/events.proto
// Plugin version: v0.0.1
//
// Generated on: 2026-09-01 10:29:06 UTC

package support

const (
	// EventsService_HandleEvent_FullMethodDescription returns the description of the alis.open.support.v1.EventsService.HandleEvent method.
	EventsService_HandleEvent_FullMethodDescription = ""
)
