// Code generated by https://github.com/alis-exchange/protoc-gen-go-meta. DO NOT EDIT.
//
// Source: alis/open/support/v1/guide.proto
// Plugin version: v0.0.1
//
// Generated on: 2026-08-03 17:30:50 UTC

package support

const (
	// GuidesService_ValidateMessage_FullMethodDescription returns the description of the alis.open.support.v1.GuidesService.ValidateMessage method.
	GuidesService_ValidateMessage_FullMethodDescription = ""
	// GuidesService_RetrieveRules_FullMethodDescription returns the description of the alis.open.support.v1.GuidesService.RetrieveRules method.
	GuidesService_RetrieveRules_FullMethodDescription = ""
	// GuidesService_GetGuide_FullMethodDescription returns the description of the alis.open.support.v1.GuidesService.GetGuide method.
	GuidesService_GetGuide_FullMethodDescription = ""
	// GuidesService_ListGuides_FullMethodDescription returns the description of the alis.open.support.v1.GuidesService.ListGuides method.
	GuidesService_ListGuides_FullMethodDescription = ""
	// GuidesService_SyncGuide_FullMethodDescription returns the description of the alis.open.support.v1.GuidesService.SyncGuide method.
	GuidesService_SyncGuide_FullMethodDescription = ""
)
