// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: alis/open/support/v1/guide.proto

package support

import (
	context "context"
	validation "go.alis.build/common/alis/open/validation"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GuidesService_ValidateMessage_FullMethodName = "/alis.open.support.v1.GuidesService/ValidateMessage"
	GuidesService_RetrieveRules_FullMethodName   = "/alis.open.support.v1.GuidesService/RetrieveRules"
	GuidesService_GetGuide_FullMethodName        = "/alis.open.support.v1.GuidesService/GetGuide"
	GuidesService_ListGuides_FullMethodName      = "/alis.open.support.v1.GuidesService/ListGuides"
	GuidesService_SyncGuide_FullMethodName       = "/alis.open.support.v1.GuidesService/SyncGuide"
)

// GuidesServiceClient is the client API for GuidesService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GuidesServiceClient interface {
	ValidateMessage(ctx context.Context, in *validation.ValidateMessageRequest, opts ...grpc.CallOption) (*validation.ValidateMessageResponse, error)
	RetrieveRules(ctx context.Context, in *validation.RetrieveRulesRequest, opts ...grpc.CallOption) (*validation.RetrieveRulesResponse, error)
	GetGuide(ctx context.Context, in *GetGuideRequest, opts ...grpc.CallOption) (*Guide, error)
	ListGuides(ctx context.Context, in *ListGuidesRequest, opts ...grpc.CallOption) (*ListGuidesResponse, error)
	SyncGuide(ctx context.Context, in *SyncGuideRequest, opts ...grpc.CallOption) (*Guide, error)
}

type guidesServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGuidesServiceClient(cc grpc.ClientConnInterface) GuidesServiceClient {
	return &guidesServiceClient{cc}
}

func (c *guidesServiceClient) ValidateMessage(ctx context.Context, in *validation.ValidateMessageRequest, opts ...grpc.CallOption) (*validation.ValidateMessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(validation.ValidateMessageResponse)
	err := c.cc.Invoke(ctx, GuidesService_ValidateMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guidesServiceClient) RetrieveRules(ctx context.Context, in *validation.RetrieveRulesRequest, opts ...grpc.CallOption) (*validation.RetrieveRulesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(validation.RetrieveRulesResponse)
	err := c.cc.Invoke(ctx, GuidesService_RetrieveRules_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guidesServiceClient) GetGuide(ctx context.Context, in *GetGuideRequest, opts ...grpc.CallOption) (*Guide, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Guide)
	err := c.cc.Invoke(ctx, GuidesService_GetGuide_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guidesServiceClient) ListGuides(ctx context.Context, in *ListGuidesRequest, opts ...grpc.CallOption) (*ListGuidesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListGuidesResponse)
	err := c.cc.Invoke(ctx, GuidesService_ListGuides_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guidesServiceClient) SyncGuide(ctx context.Context, in *SyncGuideRequest, opts ...grpc.CallOption) (*Guide, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Guide)
	err := c.cc.Invoke(ctx, GuidesService_SyncGuide_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GuidesServiceServer is the server API for GuidesService service.
// All implementations must embed UnimplementedGuidesServiceServer
// for forward compatibility.
type GuidesServiceServer interface {
	ValidateMessage(context.Context, *validation.ValidateMessageRequest) (*validation.ValidateMessageResponse, error)
	RetrieveRules(context.Context, *validation.RetrieveRulesRequest) (*validation.RetrieveRulesResponse, error)
	GetGuide(context.Context, *GetGuideRequest) (*Guide, error)
	ListGuides(context.Context, *ListGuidesRequest) (*ListGuidesResponse, error)
	SyncGuide(context.Context, *SyncGuideRequest) (*Guide, error)
	mustEmbedUnimplementedGuidesServiceServer()
}

// UnimplementedGuidesServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGuidesServiceServer struct{}

func (UnimplementedGuidesServiceServer) ValidateMessage(context.Context, *validation.ValidateMessageRequest) (*validation.ValidateMessageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ValidateMessage not implemented")
}
func (UnimplementedGuidesServiceServer) RetrieveRules(context.Context, *validation.RetrieveRulesRequest) (*validation.RetrieveRulesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RetrieveRules not implemented")
}
func (UnimplementedGuidesServiceServer) GetGuide(context.Context, *GetGuideRequest) (*Guide, error) {
	return nil, status.Error(codes.Unimplemented, "method GetGuide not implemented")
}
func (UnimplementedGuidesServiceServer) ListGuides(context.Context, *ListGuidesRequest) (*ListGuidesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListGuides not implemented")
}
func (UnimplementedGuidesServiceServer) SyncGuide(context.Context, *SyncGuideRequest) (*Guide, error) {
	return nil, status.Error(codes.Unimplemented, "method SyncGuide not implemented")
}
func (UnimplementedGuidesServiceServer) mustEmbedUnimplementedGuidesServiceServer() {}
func (UnimplementedGuidesServiceServer) testEmbeddedByValue()                       {}

// UnsafeGuidesServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GuidesServiceServer will
// result in compilation errors.
type UnsafeGuidesServiceServer interface {
	mustEmbedUnimplementedGuidesServiceServer()
}

func RegisterGuidesServiceServer(s grpc.ServiceRegistrar, srv GuidesServiceServer) {
	// If the following call panics, it indicates UnimplementedGuidesServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GuidesService_ServiceDesc, srv)
}

func _GuidesService_ValidateMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(validation.ValidateMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuidesServiceServer).ValidateMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GuidesService_ValidateMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuidesServiceServer).ValidateMessage(ctx, req.(*validation.ValidateMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GuidesService_RetrieveRules_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(validation.RetrieveRulesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuidesServiceServer).RetrieveRules(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GuidesService_RetrieveRules_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuidesServiceServer).RetrieveRules(ctx, req.(*validation.RetrieveRulesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GuidesService_GetGuide_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGuideRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuidesServiceServer).GetGuide(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GuidesService_GetGuide_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuidesServiceServer).GetGuide(ctx, req.(*GetGuideRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GuidesService_ListGuides_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListGuidesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuidesServiceServer).ListGuides(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GuidesService_ListGuides_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuidesServiceServer).ListGuides(ctx, req.(*ListGuidesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GuidesService_SyncGuide_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncGuideRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuidesServiceServer).SyncGuide(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GuidesService_SyncGuide_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuidesServiceServer).SyncGuide(ctx, req.(*SyncGuideRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GuidesService_ServiceDesc is the grpc.ServiceDesc for GuidesService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GuidesService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "alis.open.support.v1.GuidesService",
	HandlerType: (*GuidesServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ValidateMessage",
			Handler:    _GuidesService_ValidateMessage_Handler,
		},
		{
			MethodName: "RetrieveRules",
			Handler:    _GuidesService_RetrieveRules_Handler,
		},
		{
			MethodName: "GetGuide",
			Handler:    _GuidesService_GetGuide_Handler,
		},
		{
			MethodName: "ListGuides",
			Handler:    _GuidesService_ListGuides_Handler,
		},
		{
			MethodName: "SyncGuide",
			Handler:    _GuidesService_SyncGuide_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "alis/open/support/v1/guide.proto",
}
