// Code generated by https://github.com/alis-exchange/protoc-gen-go-meta. DO NOT EDIT.
//
// Source: alis/open/support/v1/issue.proto
// Plugin version: v0.0.1
//
// Generated on: 2026-08-03 16:32:36 UTC

package support

const (
	// IssuesService_ValidateMessage_FullMethodDescription returns the description of the alis.open.support.v1.IssuesService.ValidateMessage method.
	IssuesService_ValidateMessage_FullMethodDescription = ""
	// IssuesService_RetrieveRules_FullMethodDescription returns the description of the alis.open.support.v1.IssuesService.RetrieveRules method.
	IssuesService_RetrieveRules_FullMethodDescription = ""
	// IssuesService_GetIamPolicy_FullMethodDescription returns the description of the alis.open.support.v1.IssuesService.GetIamPolicy method.
	IssuesService_GetIamPolicy_FullMethodDescription = ""
	// IssuesService_SetIamPolicy_FullMethodDescription returns the description of the alis.open.support.v1.IssuesService.SetIamPolicy method.
	IssuesService_SetIamPolicy_FullMethodDescription = ""
	// IssuesService_TestIamPermissions_FullMethodDescription returns the description of the alis.open.support.v1.IssuesService.TestIamPermissions method.
	IssuesService_TestIamPermissions_FullMethodDescription = ""
	// IssuesService_AddIamBindings_FullMethodDescription returns the description of the alis.open.support.v1.IssuesService.AddIamBindings method.
	IssuesService_AddIamBindings_FullMethodDescription = ""
	// IssuesService_RemoveIamBindings_FullMethodDescription returns the description of the alis.open.support.v1.IssuesService.RemoveIamBindings method.
	IssuesService_RemoveIamBindings_FullMethodDescription = ""
	// IssuesService_CreateIssue_FullMethodDescription returns the description of the alis.open.support.v1.IssuesService.CreateIssue method.
	IssuesService_CreateIssue_FullMethodDescription = ""
	// IssuesService_UpdateIssue_FullMethodDescription returns the description of the alis.open.support.v1.IssuesService.UpdateIssue method.
	IssuesService_UpdateIssue_FullMethodDescription = ""
	// IssuesService_GetIssue_FullMethodDescription returns the description of the alis.open.support.v1.IssuesService.GetIssue method.
	IssuesService_GetIssue_FullMethodDescription = ""
	// IssuesService_ListIssues_FullMethodDescription returns the description of the alis.open.support.v1.IssuesService.ListIssues method.
	IssuesService_ListIssues_FullMethodDescription = ""
	// IssuesService_DeleteIssue_FullMethodDescription returns the description of the alis.open.support.v1.IssuesService.DeleteIssue method.
	IssuesService_DeleteIssue_FullMethodDescription = ""
	// IssuesService_EditNewIssue_FullMethodDescription returns the description of the alis.open.support.v1.IssuesService.EditNewIssue method.
	IssuesService_EditNewIssue_FullMethodDescription = ""
	// IssuesService_CancelNewIssue_FullMethodDescription returns the description of the alis.open.support.v1.IssuesService.CancelNewIssue method.
	IssuesService_CancelNewIssue_FullMethodDescription = ""
	// IssuesService_SetIssueAssignee_FullMethodDescription returns the description of the alis.open.support.v1.IssuesService.SetIssueAssignee method.
	IssuesService_SetIssueAssignee_FullMethodDescription = ""
	// IssuesService_AddIssueViewers_FullMethodDescription returns the description of the alis.open.support.v1.IssuesService.AddIssueViewers method.
	IssuesService_AddIssueViewers_FullMethodDescription = ""
	// IssuesService_RemoveIssueViewers_FullMethodDescription returns the description of the alis.open.support.v1.IssuesService.RemoveIssueViewers method.
	IssuesService_RemoveIssueViewers_FullMethodDescription = ""
)
