// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: alis/open/support/v1/issueactivity.proto

package support

import (
	context "context"
	validation "go.alis.build/common/alis/open/validation"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	IssueActivitiesService_ValidateMessage_FullMethodName     = "/alis.open.support.v1.IssueActivitiesService/ValidateMessage"
	IssueActivitiesService_RetrieveRules_FullMethodName       = "/alis.open.support.v1.IssueActivitiesService/RetrieveRules"
	IssueActivitiesService_CreateIssueActivity_FullMethodName = "/alis.open.support.v1.IssueActivitiesService/CreateIssueActivity"
	IssueActivitiesService_GetIssueActivity_FullMethodName    = "/alis.open.support.v1.IssueActivitiesService/GetIssueActivity"
	IssueActivitiesService_UpdateIssueActivity_FullMethodName = "/alis.open.support.v1.IssueActivitiesService/UpdateIssueActivity"
	IssueActivitiesService_DeleteIssueActivity_FullMethodName = "/alis.open.support.v1.IssueActivitiesService/DeleteIssueActivity"
	IssueActivitiesService_ListIssueActivities_FullMethodName = "/alis.open.support.v1.IssueActivitiesService/ListIssueActivities"
	IssueActivitiesService_CreateComment_FullMethodName       = "/alis.open.support.v1.IssueActivitiesService/CreateComment"
	IssueActivitiesService_UpdateComment_FullMethodName       = "/alis.open.support.v1.IssueActivitiesService/UpdateComment"
	IssueActivitiesService_DeleteComment_FullMethodName       = "/alis.open.support.v1.IssueActivitiesService/DeleteComment"
)

// IssueActivitiesServiceClient is the client API for IssueActivitiesService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IssueActivitiesServiceClient interface {
	ValidateMessage(ctx context.Context, in *validation.ValidateMessageRequest, opts ...grpc.CallOption) (*validation.ValidateMessageResponse, error)
	RetrieveRules(ctx context.Context, in *validation.RetrieveRulesRequest, opts ...grpc.CallOption) (*validation.RetrieveRulesResponse, error)
	CreateIssueActivity(ctx context.Context, in *CreateIssueActivityRequest, opts ...grpc.CallOption) (*IssueActivity, error)
	GetIssueActivity(ctx context.Context, in *GetIssueActivityRequest, opts ...grpc.CallOption) (*IssueActivity, error)
	UpdateIssueActivity(ctx context.Context, in *UpdateIssueActivityRequest, opts ...grpc.CallOption) (*IssueActivity, error)
	DeleteIssueActivity(ctx context.Context, in *DeleteIssueActivityRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ListIssueActivities(ctx context.Context, in *ListIssueActivitiesRequest, opts ...grpc.CallOption) (*ListIssueActivitiesResponse, error)
	CreateComment(ctx context.Context, in *CreateCommentRequest, opts ...grpc.CallOption) (*IssueActivity, error)
	UpdateComment(ctx context.Context, in *UpdateCommentRequest, opts ...grpc.CallOption) (*IssueActivity, error)
	DeleteComment(ctx context.Context, in *DeleteCommentRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type issueActivitiesServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIssueActivitiesServiceClient(cc grpc.ClientConnInterface) IssueActivitiesServiceClient {
	return &issueActivitiesServiceClient{cc}
}

func (c *issueActivitiesServiceClient) ValidateMessage(ctx context.Context, in *validation.ValidateMessageRequest, opts ...grpc.CallOption) (*validation.ValidateMessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(validation.ValidateMessageResponse)
	err := c.cc.Invoke(ctx, IssueActivitiesService_ValidateMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *issueActivitiesServiceClient) RetrieveRules(ctx context.Context, in *validation.RetrieveRulesRequest, opts ...grpc.CallOption) (*validation.RetrieveRulesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(validation.RetrieveRulesResponse)
	err := c.cc.Invoke(ctx, IssueActivitiesService_RetrieveRules_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *issueActivitiesServiceClient) CreateIssueActivity(ctx context.Context, in *CreateIssueActivityRequest, opts ...grpc.CallOption) (*IssueActivity, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IssueActivity)
	err := c.cc.Invoke(ctx, IssueActivitiesService_CreateIssueActivity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *issueActivitiesServiceClient) GetIssueActivity(ctx context.Context, in *GetIssueActivityRequest, opts ...grpc.CallOption) (*IssueActivity, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IssueActivity)
	err := c.cc.Invoke(ctx, IssueActivitiesService_GetIssueActivity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *issueActivitiesServiceClient) UpdateIssueActivity(ctx context.Context, in *UpdateIssueActivityRequest, opts ...grpc.CallOption) (*IssueActivity, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IssueActivity)
	err := c.cc.Invoke(ctx, IssueActivitiesService_UpdateIssueActivity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *issueActivitiesServiceClient) DeleteIssueActivity(ctx context.Context, in *DeleteIssueActivityRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, IssueActivitiesService_DeleteIssueActivity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *issueActivitiesServiceClient) ListIssueActivities(ctx context.Context, in *ListIssueActivitiesRequest, opts ...grpc.CallOption) (*ListIssueActivitiesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListIssueActivitiesResponse)
	err := c.cc.Invoke(ctx, IssueActivitiesService_ListIssueActivities_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *issueActivitiesServiceClient) CreateComment(ctx context.Context, in *CreateCommentRequest, opts ...grpc.CallOption) (*IssueActivity, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IssueActivity)
	err := c.cc.Invoke(ctx, IssueActivitiesService_CreateComment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *issueActivitiesServiceClient) UpdateComment(ctx context.Context, in *UpdateCommentRequest, opts ...grpc.CallOption) (*IssueActivity, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IssueActivity)
	err := c.cc.Invoke(ctx, IssueActivitiesService_UpdateComment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *issueActivitiesServiceClient) DeleteComment(ctx context.Context, in *DeleteCommentRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, IssueActivitiesService_DeleteComment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IssueActivitiesServiceServer is the server API for IssueActivitiesService service.
// All implementations must embed UnimplementedIssueActivitiesServiceServer
// for forward compatibility.
type IssueActivitiesServiceServer interface {
	ValidateMessage(context.Context, *validation.ValidateMessageRequest) (*validation.ValidateMessageResponse, error)
	RetrieveRules(context.Context, *validation.RetrieveRulesRequest) (*validation.RetrieveRulesResponse, error)
	CreateIssueActivity(context.Context, *CreateIssueActivityRequest) (*IssueActivity, error)
	GetIssueActivity(context.Context, *GetIssueActivityRequest) (*IssueActivity, error)
	UpdateIssueActivity(context.Context, *UpdateIssueActivityRequest) (*IssueActivity, error)
	DeleteIssueActivity(context.Context, *DeleteIssueActivityRequest) (*emptypb.Empty, error)
	ListIssueActivities(context.Context, *ListIssueActivitiesRequest) (*ListIssueActivitiesResponse, error)
	CreateComment(context.Context, *CreateCommentRequest) (*IssueActivity, error)
	UpdateComment(context.Context, *UpdateCommentRequest) (*IssueActivity, error)
	DeleteComment(context.Context, *DeleteCommentRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedIssueActivitiesServiceServer()
}

// UnimplementedIssueActivitiesServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIssueActivitiesServiceServer struct{}

func (UnimplementedIssueActivitiesServiceServer) ValidateMessage(context.Context, *validation.ValidateMessageRequest) (*validation.ValidateMessageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ValidateMessage not implemented")
}
func (UnimplementedIssueActivitiesServiceServer) RetrieveRules(context.Context, *validation.RetrieveRulesRequest) (*validation.RetrieveRulesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RetrieveRules not implemented")
}
func (UnimplementedIssueActivitiesServiceServer) CreateIssueActivity(context.Context, *CreateIssueActivityRequest) (*IssueActivity, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateIssueActivity not implemented")
}
func (UnimplementedIssueActivitiesServiceServer) GetIssueActivity(context.Context, *GetIssueActivityRequest) (*IssueActivity, error) {
	return nil, status.Error(codes.Unimplemented, "method GetIssueActivity not implemented")
}
func (UnimplementedIssueActivitiesServiceServer) UpdateIssueActivity(context.Context, *UpdateIssueActivityRequest) (*IssueActivity, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateIssueActivity not implemented")
}
func (UnimplementedIssueActivitiesServiceServer) DeleteIssueActivity(context.Context, *DeleteIssueActivityRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteIssueActivity not implemented")
}
func (UnimplementedIssueActivitiesServiceServer) ListIssueActivities(context.Context, *ListIssueActivitiesRequest) (*ListIssueActivitiesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListIssueActivities not implemented")
}
func (UnimplementedIssueActivitiesServiceServer) CreateComment(context.Context, *CreateCommentRequest) (*IssueActivity, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateComment not implemented")
}
func (UnimplementedIssueActivitiesServiceServer) UpdateComment(context.Context, *UpdateCommentRequest) (*IssueActivity, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateComment not implemented")
}
func (UnimplementedIssueActivitiesServiceServer) DeleteComment(context.Context, *DeleteCommentRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteComment not implemented")
}
func (UnimplementedIssueActivitiesServiceServer) mustEmbedUnimplementedIssueActivitiesServiceServer() {
}
func (UnimplementedIssueActivitiesServiceServer) testEmbeddedByValue() {}

// UnsafeIssueActivitiesServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IssueActivitiesServiceServer will
// result in compilation errors.
type UnsafeIssueActivitiesServiceServer interface {
	mustEmbedUnimplementedIssueActivitiesServiceServer()
}

func RegisterIssueActivitiesServiceServer(s grpc.ServiceRegistrar, srv IssueActivitiesServiceServer) {
	// If the following call panics, it indicates UnimplementedIssueActivitiesServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&IssueActivitiesService_ServiceDesc, srv)
}

func _IssueActivitiesService_ValidateMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(validation.ValidateMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IssueActivitiesServiceServer).ValidateMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IssueActivitiesService_ValidateMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IssueActivitiesServiceServer).ValidateMessage(ctx, req.(*validation.ValidateMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IssueActivitiesService_RetrieveRules_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(validation.RetrieveRulesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IssueActivitiesServiceServer).RetrieveRules(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IssueActivitiesService_RetrieveRules_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IssueActivitiesServiceServer).RetrieveRules(ctx, req.(*validation.RetrieveRulesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IssueActivitiesService_CreateIssueActivity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateIssueActivityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IssueActivitiesServiceServer).CreateIssueActivity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IssueActivitiesService_CreateIssueActivity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IssueActivitiesServiceServer).CreateIssueActivity(ctx, req.(*CreateIssueActivityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IssueActivitiesService_GetIssueActivity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetIssueActivityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IssueActivitiesServiceServer).GetIssueActivity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IssueActivitiesService_GetIssueActivity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IssueActivitiesServiceServer).GetIssueActivity(ctx, req.(*GetIssueActivityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IssueActivitiesService_UpdateIssueActivity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateIssueActivityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IssueActivitiesServiceServer).UpdateIssueActivity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IssueActivitiesService_UpdateIssueActivity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IssueActivitiesServiceServer).UpdateIssueActivity(ctx, req.(*UpdateIssueActivityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IssueActivitiesService_DeleteIssueActivity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteIssueActivityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IssueActivitiesServiceServer).DeleteIssueActivity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IssueActivitiesService_DeleteIssueActivity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IssueActivitiesServiceServer).DeleteIssueActivity(ctx, req.(*DeleteIssueActivityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IssueActivitiesService_ListIssueActivities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListIssueActivitiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IssueActivitiesServiceServer).ListIssueActivities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IssueActivitiesService_ListIssueActivities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IssueActivitiesServiceServer).ListIssueActivities(ctx, req.(*ListIssueActivitiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IssueActivitiesService_CreateComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCommentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IssueActivitiesServiceServer).CreateComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IssueActivitiesService_CreateComment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IssueActivitiesServiceServer).CreateComment(ctx, req.(*CreateCommentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IssueActivitiesService_UpdateComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCommentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IssueActivitiesServiceServer).UpdateComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IssueActivitiesService_UpdateComment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IssueActivitiesServiceServer).UpdateComment(ctx, req.(*UpdateCommentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IssueActivitiesService_DeleteComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCommentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IssueActivitiesServiceServer).DeleteComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IssueActivitiesService_DeleteComment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IssueActivitiesServiceServer).DeleteComment(ctx, req.(*DeleteCommentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// IssueActivitiesService_ServiceDesc is the grpc.ServiceDesc for IssueActivitiesService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IssueActivitiesService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "alis.open.support.v1.IssueActivitiesService",
	HandlerType: (*IssueActivitiesServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ValidateMessage",
			Handler:    _IssueActivitiesService_ValidateMessage_Handler,
		},
		{
			MethodName: "RetrieveRules",
			Handler:    _IssueActivitiesService_RetrieveRules_Handler,
		},
		{
			MethodName: "CreateIssueActivity",
			Handler:    _IssueActivitiesService_CreateIssueActivity_Handler,
		},
		{
			MethodName: "GetIssueActivity",
			Handler:    _IssueActivitiesService_GetIssueActivity_Handler,
		},
		{
			MethodName: "UpdateIssueActivity",
			Handler:    _IssueActivitiesService_UpdateIssueActivity_Handler,
		},
		{
			MethodName: "DeleteIssueActivity",
			Handler:    _IssueActivitiesService_DeleteIssueActivity_Handler,
		},
		{
			MethodName: "ListIssueActivities",
			Handler:    _IssueActivitiesService_ListIssueActivities_Handler,
		},
		{
			MethodName: "CreateComment",
			Handler:    _IssueActivitiesService_CreateComment_Handler,
		},
		{
			MethodName: "UpdateComment",
			Handler:    _IssueActivitiesService_UpdateComment_Handler,
		},
		{
			MethodName: "DeleteComment",
			Handler:    _IssueActivitiesService_DeleteComment_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "alis/open/support/v1/issueactivity.proto",
}
