// Code generated by https://github.com/alis-exchange/protoc-gen-go-meta. DO NOT EDIT.
//
// Source: alis/open/support/v1/issuesubscriber.proto
// Plugin version: v0.0.1
//
// Generated on: 2026-09-01 10:29:06 UTC

package support

const (
	// IssueSubscribersService_ValidateMessage_FullMethodDescription returns the description of the alis.open.support.v1.IssueSubscribersService.ValidateMessage method.
	IssueSubscribersService_ValidateMessage_FullMethodDescription = ""
	// IssueSubscribersService_RetrieveRules_FullMethodDescription returns the description of the alis.open.support.v1.IssueSubscribersService.RetrieveRules method.
	IssueSubscribersService_RetrieveRules_FullMethodDescription = ""
	// IssueSubscribersService_GetIamPolicy_FullMethodDescription returns the description of the alis.open.support.v1.IssueSubscribersService.GetIamPolicy method.
	IssueSubscribersService_GetIamPolicy_FullMethodDescription = ""
	// IssueSubscribersService_SetIamPolicy_FullMethodDescription returns the description of the alis.open.support.v1.IssueSubscribersService.SetIamPolicy method.
	IssueSubscribersService_SetIamPolicy_FullMethodDescription = ""
	// IssueSubscribersService_TestIamPermissions_FullMethodDescription returns the description of the alis.open.support.v1.IssueSubscribersService.TestIamPermissions method.
	IssueSubscribersService_TestIamPermissions_FullMethodDescription = ""
	// IssueSubscribersService_AddIamBindings_FullMethodDescription returns the description of the alis.open.support.v1.IssueSubscribersService.AddIamBindings method.
	IssueSubscribersService_AddIamBindings_FullMethodDescription = ""
	// IssueSubscribersService_RemoveIamBindings_FullMethodDescription returns the description of the alis.open.support.v1.IssueSubscribersService.RemoveIamBindings method.
	IssueSubscribersService_RemoveIamBindings_FullMethodDescription = ""
	// IssueSubscribersService_CreateIssueSubscriber_FullMethodDescription returns the description of the alis.open.support.v1.IssueSubscribersService.CreateIssueSubscriber method.
	IssueSubscribersService_CreateIssueSubscriber_FullMethodDescription = ""
	// IssueSubscribersService_GetIssueSubscriber_FullMethodDescription returns the description of the alis.open.support.v1.IssueSubscribersService.GetIssueSubscriber method.
	IssueSubscribersService_GetIssueSubscriber_FullMethodDescription = ""
	// IssueSubscribersService_ListIssueSubscribers_FullMethodDescription returns the description of the alis.open.support.v1.IssueSubscribersService.ListIssueSubscribers method.
	IssueSubscribersService_ListIssueSubscribers_FullMethodDescription = ""
	// IssueSubscribersService_DeleteIssueSubscriber_FullMethodDescription returns the description of the alis.open.support.v1.IssueSubscribersService.DeleteIssueSubscriber method.
	IssueSubscribersService_DeleteIssueSubscriber_FullMethodDescription = ""
)
