// Code generated by https://github.com/alis-exchange/protoc-gen-go-meta. DO NOT EDIT.
//
// Source: alis/open/support/v1/issueactivity.proto
// Plugin version: v0.0.1
//
// Generated on: 2026-08-24 16:39:03 UTC

package support

const (
	// IssueActivitiesService_ValidateMessage_FullMethodDescription returns the description of the alis.open.support.v1.IssueActivitiesService.ValidateMessage method.
	IssueActivitiesService_ValidateMessage_FullMethodDescription = ""
	// IssueActivitiesService_RetrieveRules_FullMethodDescription returns the description of the alis.open.support.v1.IssueActivitiesService.RetrieveRules method.
	IssueActivitiesService_RetrieveRules_FullMethodDescription = ""
	// IssueActivitiesService_CreateIssueActivity_FullMethodDescription returns the description of the alis.open.support.v1.IssueActivitiesService.CreateIssueActivity method.
	IssueActivitiesService_CreateIssueActivity_FullMethodDescription = ""
	// IssueActivitiesService_GetIssueActivity_FullMethodDescription returns the description of the alis.open.support.v1.IssueActivitiesService.GetIssueActivity method.
	IssueActivitiesService_GetIssueActivity_FullMethodDescription = ""
	// IssueActivitiesService_UpdateIssueActivity_FullMethodDescription returns the description of the alis.open.support.v1.IssueActivitiesService.UpdateIssueActivity method.
	IssueActivitiesService_UpdateIssueActivity_FullMethodDescription = ""
	// IssueActivitiesService_DeleteIssueActivity_FullMethodDescription returns the description of the alis.open.support.v1.IssueActivitiesService.DeleteIssueActivity method.
	IssueActivitiesService_DeleteIssueActivity_FullMethodDescription = ""
	// IssueActivitiesService_ListIssueActivities_FullMethodDescription returns the description of the alis.open.support.v1.IssueActivitiesService.ListIssueActivities method.
	IssueActivitiesService_ListIssueActivities_FullMethodDescription = ""
	// IssueActivitiesService_CreateComment_FullMethodDescription returns the description of the alis.open.support.v1.IssueActivitiesService.CreateComment method.
	IssueActivitiesService_CreateComment_FullMethodDescription = ""
	// IssueActivitiesService_UpdateComment_FullMethodDescription returns the description of the alis.open.support.v1.IssueActivitiesService.UpdateComment method.
	IssueActivitiesService_UpdateComment_FullMethodDescription = ""
	// IssueActivitiesService_DeleteComment_FullMethodDescription returns the description of the alis.open.support.v1.IssueActivitiesService.DeleteComment method.
	IssueActivitiesService_DeleteComment_FullMethodDescription = ""
)
