// Code generated by https://github.com/alis-exchange/protoc-gen-go-meta. DO NOT EDIT.
//
// Source: alis/open/iam/v1/iam.proto
// Plugin version: v0.0.1
//
// Generated on: 2026-08-03 17:31:40 UTC

package iam

const ()
