// Code generated by https://github.com/alis-exchange/protoc-gen-go-meta. DO NOT EDIT.
//
// Source: alis/open/iam/v1/iam.proto
// Plugin version: v0.0.1
//
// Generated on: 2026-09-01 13:22:10 UTC

package iam

const ()
