// Code generated by https://github.com/alis-exchange/protoc-gen-go-meta. DO NOT EDIT.
//
// Source: alis/open/iam/v1/role.proto
// Plugin version: v0.0.1
//
// Generated on: 2026-09-02 16:38:57 UTC

package iam

const ()
