// Code generated by https://github.com/alis-exchange/protoc-gen-go-meta. DO NOT EDIT.
//
// Source: alis/open/pubsub/v1/pubsub.proto
// Plugin version: v0.0.1
//
// Generated on: 2026-09-02 16:32:59 UTC

package pubsub

const ()
