// Code generated by https://github.com/alis-exchange/protoc-gen-go-meta. DO NOT EDIT.
//
// Source: alis/open/px/v1/px.proto
// Plugin version: v0.0.1
//
// Generated on: 2026-09-02 16:33:02 UTC

package px

const ()
